### ISSUE TITLE
Can't update key, unless in array, with dot.str

### ISSUE THREAD

**Issue by DaveBitter** [rhalff/dot-object#34]
Hi, I just found out that if you want to update a key in an object with dot.str you can't do that:

```js
const original = {
    a: 1,
    b: 2
}

dot.str("a", "Some string", original)

// results in:
// {
// 	a: 1,
// 	b: 2
// }
```  

But while updating a key in an object in an array it works perfectly fine:

```js
const original = {
    arr: [{
        a: 1,
	b: 2
    }]
};

dot.str('arr.0.a', "Some string", original);

// results in:
// {
//   arr: [{
// 		a: "Some string",
// 		b: 2
// 	}]
// }
```

I can imagine that you can update the key of an object in an array because the order might have changed and it could be an other object. It would be great to either do the same for both or console.warn if you try to this. This should also be in the docs.

Cheers

**Comment by itaibaruch** [comment]
Hi, a quick solution it to remove the key and then use dot.str:

**Comment by DaveBitter** [comment]
Hi, thanks for the suggestion! This seems like a good workaround indeed. Is there a reason why you wouldn't be able to do it directly?

**Comment by Mayhem93** [comment]
The issue is not specific only to this case. Generally, `dot.str()` doesn't work with root level fields:
![image](https://user-images.githubusercontent.com/705289/57525784-4daa2280-7334-11e9-8a34-ac54c30a79e7.png)

Can we get this fixed ? As it turns it out, it's actually a bug, and root level fields should be able to be accessed (at least through the **str** function)
